font_size 12.0
font_family Iosevka NFM
confirm_os_window_close 0
disable_ligatures always
window_padding_width 4

###########
## theme ##
###########

### kanso-zen
background #090E13
foreground #C5C9C7
selection_background #393B44
selection_foreground #C5C9C7
url_color #72A7BC
cursor #C5C9C7
cursor_text_color #090E13
# Tabs
active_tab_background #090E13
active_tab_foreground #C5C9C7
inactive_tab_background  #090E13
inactive_tab_foreground #A4A7A4
# normal
color0 #0d0c0c
color1 #c4746e
color2 #8a9a7b
color3 #c4b28a
color4 #8ba4b0
color5 #a292a3
color6 #8ea4a2
color7 #C8C093
# bright
color8  #A4A7A4
color9  #E46876
color10 #87a987
color11 #E6C384
color12 #7FB4CA
color13 #938AA9
color14 #7AA89F
color15 #C5C9C7
# extended colors
color16 #b6927b
color17 #b98d7b

# ### rosé pine
# foreground               #e0def4
# background               #191724
# selection_foreground     #e0def4
# selection_background     #403d52
# cursor                   #524f67
# cursor_text_color        #e0def4
# url_color                #c4a7e7
# active_tab_foreground    #e0def4
# active_tab_background    #26233a
# inactive_tab_foreground  #6e6a86
# inactive_tab_background  #191724
# active_border_color      #31748f
# inactive_border_color    #403d52
# # black
# color0   #26233a
# color8   #6e6a86
# # red
# color1   #eb6f92
# color9   #eb6f92
# # green
# color2   #31748f
# color10  #31748f
# # yellow
# color3   #f6c177
# color11  #f6c177
# # blue
# color4   #9ccfd8
# color12  #9ccfd8
# # magenta
# color5   #c4a7e7
# color13  #c4a7e7
# # cyan
# color6   #ebbcba
# color14  #ebbcba
# # white
# color7   #e0def4
# color15  #e0def4

# ### kanagawa dragon
# foreground                      #c5c9c5
# background                      #181616
# selection_foreground            #c8c093
# selection_background            #2d4f67
# cursor                          #c8c093
# url_color                       #72a7bc
# active_tab_foreground           #c8c093
# active_tab_background           #12120f
# inactive_tab_foreground         #a6a69c
# inactive_tab_background         #12120f
# # black
# color0  #0d0c0c
# color8  #a6a69c
# # red
# color1  #c4746e
# color9  #e46876
# # green
# color2  #8a9a7b
# color10 #87a987
# # yellow
# color3  #c4b28a
# color11 #e6c384
# # blue
# color4  #8ba4b0
# color12 #7fb4ca
# # magenta
# color5  #a292a3
# color13 #938aa9
# # cyan
# color6  #8ea4a2
# color14 #7aa89f
# # white
# color7  #c8c093
# color15 #c5c9c5
# # You can set the remaining 240 colors as color16 to color255.
# color16 #b6927b
# color17 #b98d7b

############
## splits ##
############
map ctrl+shift+enter launch --location=hsplit
map ctrl+shift+o next_layout

map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right
