font_size 16.0
font_family Hurmit Nerd Font Mono

confirm_os_window_close 0
hide_window_decorations titlebar-only
window_margin_width 8

#####################
## Kanagawa Dragon ##
#####################
foreground            #C5C9C5
background            #181616
selection_foreground  #C8C093
selection_background  #2D4F67
url_color             #C5C9C5
cursor                #C8C093
# black
color0  #0D0C0C
color8  #A6A69C
# red
color1  #C4746E
color9  #E46876
# green
color2  #8A9A7B
color10 #87A987
# yellow
color3  #C4B28A
color11 #E6C384
# blue
color4  #8BA4B0
color12 #7FB4CA
# magenta
color5  #A292A3
color13 #938AA9
# cyan
color6  #8EA4A2
color14 #7AA89F
# white
color7  #C8C093
color15 #C5C9C5

##########
## Nord ##
##########
# foreground            #D8DEE9
# background            #2E3440
# selection_foreground  #000000
# selection_background  #FFFACD
# url_color             #0087BD
# cursor                #81A1C1
# # black
# color0   #3B4252
# color8   #4C566A
# # red
# color1   #BF616A
# color9   #BF616A
# # green
# color2   #A3BE8C
# color10  #A3BE8C
# # yellow
# color3   #EBCB8B
# color11  #EBCB8B
# # blue
# color4  #81A1C1
# color12 #81A1C1
# # magenta
# color5   #B48EAD
# color13  #B48EAD
# # cyan
# color6   #88C0D0
# color14  #8FBCBB
# # white
# color7   #E5E9F0
# color15  #ECEFF4
