enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

gaps.inner.horizontal = 12
gaps.inner.vertical =   12
gaps.outer.left =       8
gaps.outer.bottom =     8
gaps.outer.top =        8
gaps.outer.right =      8

after-startup-command = [
    'exec-and-forget /opt/homebrew/bin/borders active_color=0xffa3be8c inactive_color=0xff434c5e width=8.0'
]

[mode.main.binding]
alt-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty -1 -d /Users/tkerr'
alt-shift-q = 'close'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-f = 'fullscreen'

ctrl-alt-h = 'split horizontal'
ctrl-alt-j = 'split vertical'
ctrl-alt-k = 'split vertical'
ctrl-alt-l = 'split horizontal'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-n = 'move-workspace-to-monitor --wrap-around next'
alt-shift-p = 'move-workspace-to-monitor --wrap-around prev'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
